### ISSUE TITLE
Week 2: Install Reticulate Package in R.

### ISSUE THREAD

**Issue by Mojoo-Star** [CubeStatistica/Professional-Training-for-Data-Science-Team-Statistics#19]

**Comment by Mojoo-Star** [comment]
- [ ] @Jaybo44 
- [ ] @Mojoo-Star 
- [ ] @Abdullahsulehri10 
- [ ] @shamza0 
- [ ] @Maryam-22844

**Comment by shamza0** [comment]
On which days tutorial have we covered this?

**Comment by Mojoo-Star** [comment]
> On which days tutorial have we covered this? @moniza22

Last weekend class. We only installed the package

**Comment by moniza22** [comment]
@shamza0 last weekend
